-- 스키마 생성
CREATE SCHEMA S_COIN;
CREATE SCHEMA S_CORPORATE;
CREATE SCHEMA S_NOTIFICATION;
CREATE SCHEMA S_STOCK;
CREATE SCHEMA S_USER;

-- 사용자 생성
CREATE USER BTC WITH PASSWORD '1234';
CREATE USER COI WITH PASSWORD '1234';
CREATE USER CRP WITH PASSWORD '1234';
CREATE USER NTF WITH PASSWORD '1234';
CREATE USER STC  WITH PASSWORD '1234';
CREATE USER USR WITH PASSWORD '1234';

-- 권한 부여
GRANT ALL PRIVILEGES ON SCHEMA S_CORPORATE TO BTC ;
GRANT ALL PRIVILEGES ON SCHEMA S_COIN TO COI ;
GRANT ALL PRIVILEGES ON SCHEMA S_CORPORATE TO CRP ;
GRANT ALL PRIVILEGES ON SCHEMA S_NOTIFICATION TO NTF ;
GRANT ALL PRIVILEGES ON SCHEMA S_STOCK TO STC  ;
GRANT ALL PRIVILEGES ON SCHEMA S_USER TO USR ;

/*
GRANT ALL PRIVILEGES ON TABLE s_corporate.p_corporate_codes TO crp;
GRANT ALL PRIVILEGES ON TABLE s_corporate.p_corporate_major_finance TO crp;
 */
