server:
  port: 19094

spring:
  application:
    name: corporate

  datasource:
    url: ${CRP_POSTGRES_URL}
    username: crp
    password: ${CRP_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  elasticsearch:
    uris: ${ELASTICCLOUD_ENDPOINT}
    username: elastic
    password: ${ELASTICCLOUD_PASSWORD}
  data:
    redis:
      host: ${ELASTICACHE_REDIS_HOST}
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

logging:
  file:
    name: corporate/src/main/logs/corporate.log
  level:
    root: INFO