server:
  port: 19094

spring:
  application:
    name: corporate

  datasource:
    url: jdbc:postgresql://localhost:5432/tradingtrends
    username: crp
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  elasticsearch:
    uris: ${ELASTICCLOUD_ENDPOINT}
    username: elastic
    password: ${ELASTICCLOUD_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  file:
    name: corporate/src/main/logs/corporate.log
  level:
    root: INFO
