server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/member/**
        - id: corporate
          uri: lb://corporate
          predicates:
            - Path=/api/corporate-report/**, /api/corporate-major-finance/**, /api/interested-corporate/**
        - id: stock
          uri: lb://stock
          predicates:
            - Path=/stock/**
        - id: coin
          uri: lb://coin
          predicates:
            - Path=/api/coin/**, /api/interested-coin/**, /connect-websocket, /disconnect-websocket, /api/subscription/**
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/notification/**
        - id: batch
          uri: lb://batch
          predicates:
            - Path=/api/data-collection/**
        - id: common
          uri: lb://common
          predicates:
            - Path=/common/**
        - id: market
          uri: lb://market
          predicates:
            - Path=/api/subscription, /api/subscription/**
      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.http.server: DEBUG   # 네티 서버 디버깅
    org.springframework.boot.autoconfigure.web: DEBUG  # 웹 요청 관련 디버깅
    org.springframework.http: DEBUG  # HTTP 요청 관련 디버깅
    org.springframework.cloud.gateway.filter: DEBUG  # 게이트웨이 필터 디버깅
    org.springframework.cloud.gateway.route: DEBUG   # 게이트웨이 경로 매칭 디버깅

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    prefer-ip-address: true  # Eureka에서 IP 주소를 우선 사용하게 설정
