server:
  port: 19100

spring:
  application:
    name: market

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: market-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Kafka 메세지의 키를 문자열로 역직렬화
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # Kafka 메세지의 값을 JSON으로 역직렬화
      auto-offset-reset: latest # 메세지 읽는 순서
      properties:
        spring.json.trusted.packages: '*'
        allow.auto.create.topic: false # 코드에서 토픽 자동 생성을 막음
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # Kafka 메시지의 키를 문자열로 직렬화
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Kafka 메세지의 값을 JSON으로 직렬화

  data:
    redis:
      host: localhost
      port: 26379
      password: systempass
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


