server:
  port: 19092

spring:
  application:
    name: auth

  data:
    redis:
      host: localhost   # Docker를 사용할 경우 컨테이너 이름으로도 가능 (예: redis-stack-compose)
      port: 26379
      password: systempass  # 실제 비밀번호로 교체

service:
  jwt:
    access-expiration: 360000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
