server:
  port: 19096

spring:
  application:
    name: coin

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/postgres
    username: coi
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 1000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Kafka 메세지의 키를 문자열로 역직렬화
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # Kafka 메세지의 값을 JSON으로 역직렬화
      auto-offset-reset: latest # 메세지 읽는 순서
      properties:
        spring.json.trusted.packages: '*'
        allow.auto.create.topic: false # 코드에서 토픽 자동 생성을 막음
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # Kafka 메시지의 키를 문자열로 직렬화
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # Kafka 메세지의 값을 JSON으로 직렬화

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


