# 순서대로 해주세요

# @name Step 1 : 유저 ID 별 수신 웹소켓 연결 - Postman WebScoket Template 이용
url : ws://localhost:19100/ws/connect/coin-data-per-user?userId=1

###

# @name Step 2 : 유저가 원하는 종목 Redis 채널 발행
# 비트코인 실시간 데이터
POST http://localhost:19100/api/subscription/subscribe/1/KRW-BTC
Content-Type: application/json

###

# @name Step 3 : Upbit WebSocket 연결 API
POST http://localhost:19096/api/coin/connect-websocket
Content-Type: application/json

###

# @name STep 4 : Upbit WebSocket 해제 API
POST http://localhost:19096/api/coin/disconnect-websocket
Content-Type: application/json