spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradingtrends
    username: btc
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
  elasticsearch:
    uris: 0.0.0.0:9200



eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


dart:
  api-key: ${DART-API-KEY}
  list-url: https://opendart.fss.or.kr/api/list.json
  document-url: https://opendart.fss.or.kr/api/document.xml

logging:
  level:
    org:
      springframework: DEBUG