spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradingtrends
    username: btc
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
  elasticsearch:
    uris: 0.0.0.0:9200




eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


dart:
  api-key: d83d36e85eaf57017b6af0f4b9f269f76ae11328
  corp-code-url: https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key=
  corp-finance-url: https://opendart.fss.or.kr/api/fnlttSinglIndx.json
  list-url: https://opendart.fss.or.kr/api/list.json
  document-url: https://opendart.fss.or.kr/api/document.xml
  batch-time: 04:00
