name: CI for Eureka Module

on:
  push:
    paths:
      - 'eureka/**'
  workflow_dispatch:  # 수동 실행을 위한 이벤트 추가

permissions:  # GITHUB_TOKEN에 대한 권한 설정
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application-secret.yml
        run: |
          mkdir -p eureka/src/main/resources  # 경로가 없을 경우 생성
          cd eureka/src/main/resources
          # touch ./application-secret.yml
          echo "${{ secrets.APPLICATION_PROD_EUREKA_YML }}" > ./application-secret.yml 

      - name: Update application.yml for secrets profile
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml 

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradlew에 실행 권한 추가
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Auth Service
        run: ./gradlew :eureka:build -x test

      # .ssh 디렉토리 생성
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      # 원격 서버의 호스트 키를 등록
      - name: Add remote server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_EC2_TRADING_TRENDS_DNS }} >> ~/.ssh/known_hosts

      # SSH 개인 키를 에이전트에 추가
      - name: Add SSH private key
        run: |
          echo "${{ secrets.AWS_EC2_SERVICES_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          scp -r ./eureka ubuntu@${{ secrets.AWS_EC2_TRADING_TRENDS_DNS }}:${{ secrets.AWS_EC2_TRADINGTRENDS_DEPLOY_PATH }}
          ssh ubuntu@${{ secrets.AWS_EC2_TRADING_TRENDS_DNS }} << EOF
          # 19090 포트에서 실행 중인 프로세스를 확인하고 종료
          if lsof -i :19090 -t >/dev/null; then
            echo "Stopping existing service on port 19090..."
            kill -9 \$(lsof -i :19090 -t)
          else
            echo "No service running on port 19090."
          fi

          # 새로 서비스 시작
          cd ${{ secrets.AWS_EC2_TRADINGTRENDS_DEPLOY_JAR_PATH_EUREKA }}
          nohup java -jar -Dspring.profiles.active=secret eureka-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
          EOF

      - name: Trigger CI for All Other Modules
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Trading-Trends/Trading-Trends/dispatches \
          -d '{"event_type":"trigger-all-modules"}'


